# -*- coding: utf-8 -*-
"""1stColabNotebook-29thMay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEETwYG0njXdDvwFj_wfL5CcXAP_h123

Hierarchical Agglomerative Clustering
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from scipy.cluster.hierarchy import linkage

data = {
    "User_ID": ["U1","U2","U3","U4","U5"],
    "Basket_Size": [12,2,15,3,8],
    "Total_Spent": [140,15,180,22,95]
}

df = pd.DataFrame(data)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df[["Basket_Size","Total_Spent"]])

Z = linkage(scaled, method="ward")

print(Z)

"""Dendrogram Plot"""

import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram

plt.figure(figsize=(8,5))

dendrogram(
    Z,
    labels=df["UserID"].values
)

plt.title("Dendrogram")
plt.xlabel("Basket_Size")
plt.ylabel("Total_Spent")
plt.show()

"""Hierarchical Dendrogram"""

plt.figure(figsize=(8,5))

dendrogram(
    Z,
    labels=df["UserID"].values,
    leaf_rotation=90
)

plt.title("Dendrogram diagram")
plt.xlabel("Customer Records")
plt.ylabel("Distance")
plt.show()

"""1st Problem Verification"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
data = {
    "BasketSize": [12, 2, 15, 3, 8],
    "TotalSpent": [140, 15, 180, 22, 95]
}
df = pd.DataFrame(data)
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)
scaled_df = pd.DataFrame(scaled, columns=["BasketSize", "TotalSpent"])
print(scaled_df)